<a href="https://colab.research.google.com/github/Mahadeva77/Mahadeva1/blob/main/program_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
df = pd.DataFrame({ "Order Date": [ "2024-01-10", "2024-01-15", "2024-02-05", "2024-02-12", "2024-03-01", "2024-03-15", "2024-04-10", "2024-04-20", "2024-05-05", "2024-01-15" ],
                   "Product Name": ["Laptop","Mouse","Printer","Tablet","Laptop","Monitor","Mouse","Printer","Smartwatch","Mouse"],
                    "category":["Electronics","Accessories","Office","Electronics","Electronics","Accessories","Accessories","Office","Electronics","Accessories"],
                    "Region":["North","South","East","West","North","South","East","West","North","South"],
                    "Quality":[2,5,3,4,1,2,6,2,3,5],
                    "Sales":[50000,2500,9000,30000,55000,16000,3000,6000,45000,2500],
                    "Profit":[10000,500,1500,6000,11000,3000,None,1000,9000,500]
})
print("ORIGINAL DATASET")
display(df)

ORIGINAL DATASET

   Order Date Product Name     category Region  Quality  Sales   Profit
0  2024-01-10       Laptop  Electronics  North        2  50000  10000.0
1  2024-01-15        Mouse  Accessories  South        5   2500    500.0
2  2024-02-05      Printer       Office   East        3   9000   1500.0
3  2024-02-12       Tablet  Electronics   West        4  30000   6000.0
4  2024-03-01       Laptop  Electronics  North        1  55000  11000.0
5  2024-03-15      Monitor  Accessories  South        2  16000   3000.0
6  2024-04-10        Mouse  Accessories   East        6   3000      NaN
7  2024-04-20      Printer       Office   West        2   6000   1000.0
8  2024-05-05   Smartwatch  Electronics  North        3  45000   9000.0
9  2024-01-15        Mouse  Accessories  South        5   2500    500.0

In [ ]:
print("FIRST 5 RECORDS")
display(df.head())
display(df.tail())

FIRST 5 RECORDS

   Order Date Product Name     category Region  Quality  Sales   Profit
0  2024-01-10       Laptop  Electronics  North        2  50000  10000.0
1  2024-01-15        Mouse  Accessories  South        5   2500    500.0
2  2024-02-05      Printer       Office   East        3   9000   1500.0
3  2024-02-12       Tablet  Electronics   West        4  30000   6000.0
4  2024-03-01       Laptop  Electronics  North        1  55000  11000.0

   Order Date Product Name     category Region  Quality  Sales  Profit
5  2024-03-15      Monitor  Accessories  South        2  16000  3000.0
6  2024-04-10        Mouse  Accessories   East        6   3000     NaN
7  2024-04-20      Printer       Office   West        2   6000  1000.0
8  2024-05-05   Smartwatch  Electronics  North        3  45000  9000.0
9  2024-01-15        Mouse  Accessories  South        5   2500   500.0

In [ ]:
print("DATASET SHAPE")
print(df.shape)

DATASET SHAPE
(10, 7)

In [ ]:
print("COLUMN NAMES")
print(df.columns)

COLUMN NAMES
Index(['Order Date', 'Product Name', 'category', 'Region', 'Quality', 'Sales',
       'Profit'],
      dtype='object')

In [5]:
print(df.info)

<bound method DataFrame.info of    Order Date Product Name     category Region  Quality  Sales   Profit
0  2024-01-10       Laptop  Electronics  North        2  50000  10000.0
1  2024-01-15        Mouse  Accessories  South        5   2500    500.0
2  2024-02-05      Printer       Office   East        3   9000   1500.0
3  2024-02-12       Tablet  Electronics   West        4  30000   6000.0
4  2024-03-01       Laptop  Electronics  North        1  55000  11000.0
5  2024-03-15      Monitor  Accessories  South        2  16000   3000.0
6  2024-04-10        Mouse  Accessories   East        6   3000      NaN
7  2024-04-20      Printer       Office   West        2   6000   1000.0
8  2024-05-05   Smartwatch  Electronics  North        3  45000   9000.0
9  2024-01-15        Mouse  Accessories  South        5   2500    500.0>

In [ ]:
print("DATA TYPES")
print(df.dtypes)
print("DESCRIPTIVE STATISTICS")
display(df.describe())

DATA TYPES
Order Date       object
Product Name     object
category         object
Region           object
Quality           int64
Sales             int64
Profit          float64
dtype: object
DESCRIPTIVE STATISTICS

         Quality         Sales        Profit
count  10.000000     10.000000      9.000000
mean    3.300000  21900.000000   4722.222222
std     1.636392  21209.012759   4330.928820
min     1.000000   2500.000000    500.000000
25%     2.000000   3750.000000   1000.000000
50%     3.000000  12500.000000   3000.000000
75%     4.750000  41250.000000   9000.000000
max     6.000000  55000.000000  11000.000000

In [ ]:
print("MISSING VALUES")
print(df.isnull().sum())
print("ROWS CONTAINING MISSING VALUES")
display(df[df.isnull().any(axis=1)])
print("TOTAL DUPLICATE RECORDS")
print(df.duplicated().sum())
print("DUPLICATE RECORDS")
display(df[df.duplicated()])

MISSING VALUES
Order Date      0
Product Name    0
category        0
Region          0
Quality         0
Sales           0
Profit          1
dtype: int64
ROWS CONTAINING MISSING VALUES

   Order Date Product Name     category Region  Quality  Sales  Profit
6  2024-04-10        Mouse  Accessories   East        6   3000     NaN

TOTAL DUPLICATE RECORDS
1
DUPLICATE RECORDS

   Order Date Product Name     category Region  Quality  Sales  Profit
9  2024-01-15        Mouse  Accessories  South        5   2500   500.0